"use client";

import { FileText, Shield } from "lucide-react";
import { SectionHeading, SectionLabel } from "@/components/shared/BrandTypography";
import { AppFooter } from "@/components/layout/AppFooter";

const bgGradient = "radial-gradient(circle at 50% 0%, rgba(0, 150, 254, 0.12) 0%, transparent 60%), radial-gradient(ellipse 70% 60% at 50% 100%, rgba(0, 150, 254, 0.22) 0%, transparent 100%)";

export default function TermsPage() {
  return (
    <div className="min-h-screen px-4 pt-32 pb-16 relative overflow-hidden" style={{ background: bgGradient }}>
      {/* Ambient backgrounds */}
      <div className="pointer-events-none fixed inset-0 overflow-hidden z-0">
        <div className="animate-float-orb absolute -top-40 left-[30%] h-[600px] w-[600px] rounded-full blur-3xl"
          style={{ background: "rgba(0, 150, 254, 0.10)" }} />
        <div className="animate-float-orb-delayed absolute top-1/3 -right-32 h-96 w-96 rounded-full blur-3xl"
          style={{ background: "rgba(0, 150, 254, 0.08)" }} />
        <div className="dot-pattern absolute inset-0 opacity-[0.35]" />
      </div>

      <div className="mx-auto max-w-3xl relative z-10">
        <div className="text-center mb-16">
          <SectionLabel>
            <FileText className="h-3 w-3 text-blue-400" />
            Legal Documentation
          </SectionLabel>
          <SectionHeading gray="Terms of" blue="Service" />
          <p className="text-xs text-white/30 mt-2">Last Updated: June 13, 2026</p>
        </div>

        <div className="rounded-2xl border border-white/8 bg-[#0a0a0a]/60 backdrop-blur-md p-8 md:p-12 text-white/70 space-y-8 text-sm leading-relaxed">
          <section className="space-y-3">
            <h3 className="font-serif text-lg font-bold text-white/90 flex items-center gap-2.5">
              <span className="text-blue-400 text-xs">01 /</span> Acceptance of Terms
            </h3>
            <p>
              By accessing or using the Code Sphere website and services, you agree to comply with and be bound by these Terms of Service. If you do not agree to these terms, please refrain from using our services.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="font-serif text-lg font-bold text-white/90 flex items-center gap-2.5">
              <span className="text-blue-400 text-xs">02 /</span> User Accounts & Registration
            </h3>
            <p>
              To access custom app-generation features, you must register for an account. You are responsible for keeping your credentials confidential and are fully responsible for all actions occurring under your account.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="font-serif text-lg font-bold text-white/90 flex items-center gap-2.5">
              <span className="text-blue-400 text-xs">03 /</span> Usage Allocations & Token Limits
            </h3>
            <p>
              Code Sphere allocates limits to user accounts for code generation based on their subscription tier:
            </p>
            <ul className="list-disc list-inside pl-4 space-y-1.5 text-white/65">
              <li><strong>Free Plan:</strong> Limited to 10 generations and 100,000 tokens lifetime usage.</li>
              <li><strong>Starter Plan:</strong> Limited to 50 generations/month and 500,000 tokens usage.</li>
              <li><strong>Pro Plan:</strong> Limited to 150 generations/month and 2,000,000 tokens usage.</li>
            </ul>
            <p>
              If your generation total or token usage exceeds these allocations, services will be paused until the next billing cycle or until a tier upgrade is purchased.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="font-serif text-lg font-bold text-white/90 flex items-center gap-2.5">
              <span className="text-blue-400 text-xs">04 /</span> Intellectual Property Rights
            </h3>
            <p>
              You retain all ownership rights to the structural prompts you input. Code Sphere grants you a non-exclusive, worldwide, royalty-free license to use, copy, modify, and distribute any source code generated by the service for commercial or personal projects.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="font-serif text-lg font-bold text-white/90 flex items-center gap-2.5">
              <span className="text-blue-400 text-xs">05 /</span> Disclaimer of Warranties
            </h3>
            <p>
              THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. CODE SPHERE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT GUARANTEE GENERATED CODE WILL BE ERROR-FREE.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="font-serif text-lg font-bold text-white/90 flex items-center gap-2.5">
              <span className="text-blue-400 text-xs">06 /</span> Limitation of Liability
            </h3>
            <p>
              In no event shall Code Sphere be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or system downtime resulting from your use of or inability to use the service.
            </p>
          </section>
        </div>
      </div>

      <AppFooter />
    </div>
  );
}
